### ISSUE TITLE
Formalise date format

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/rfcs#47]
It looks like the RFC's use a multitude of different date formats.
I have spotted: MMDDYY, DDMMYY, DD Month YY etc. 
We need to pick one and update all dates to the specified one

**Comment by SWvheerden** [comment]
My vote would be for DDMMYY

**Comment by stringhandler** [comment]
Mine would be for long format or sortable DD MMM YYYY, or YYYY-MM-DD

**Comment by SWvheerden** [comment]
Perhaps a long format is better, MMDD and DDMM can cause some confusion.

**Comment by delta1** [comment]
ISO 8601 or death

**Comment by AaronFeickert** [comment]
> ISO 8601 or death

Yeah, I'd say go with ISO-8601. It's standardized, good for sorting, and pretty unambiguous.

**Comment by CjS77** [comment]
Looks like we've organically converged on `dd MMM yyyy`
