### ISSUE TITLE
RFC 313 - The ordering of the VN set is not correct

### ISSUE THREAD

**Issue by stringhandler** [tari-project/rfcs#73]
in https://rfc.tari.com/RFC-0313_VNRegistration.html#validator-node-set-definition

```
The function get_vn_set(ϵstart,ϵend)→S⃗  that returns an ordered vector S⃗  of VN_Shard_Keys that are registered for the epoch ϵn. As all UTXOs are already ordered in the base layer, we can rely on deterministic ordering based on order the registration [UTXO](https://rfc.tari.com/Glossary.html#unspent-transaction-outputs)s are placed in the blockchain.
```

This should read "The order is based on the VN_Shard_Key"

**Comment by sdbondi** [comment]
Any reason to impose this ordering? The blockchain already provides canonical ordering.

**Comment by sdbondi** [comment]
Explained in chat: we trade off the very small cost of ordering by shard id for smaller Merkle proofs in QCs (if leaf nodes included in the proof are nearer to each other, then proofs are smaller)
