### ISSUE TITLE
RFC-0153: Forward security issues with Stage 1b

### ISSUE THREAD

**Issue by stringhandler** [tari-project/rfcs#77]
If a user's seed words are stored in the unencrypted database on the cloud and the user's cloud is compromised, the attacker can steal future funds because they have the seed words. 

I don't have a solution right now, but potentially: making a change to remove the seed words from the unencrypted db and maybe generating new seed words for recovery.

**Comment by stringhandler** [comment]
it is accounted for, my bad

**Comment by CjS77** [comment]
Not just a pretty face :)
